### ISSUE TITLE
Prepare bitbucket workflow

### ISSUE THREAD

**Issue by michaltomczuk** [opsd-io/terraform-project-template#3]

**Comment by jakub-kubera** [comment]
https://bitbucket.org/jk-repos/run_pipeline/src/main/

**Comment by jakub-kubera** [comment]
https://bitbucket.org/jk-repos/run_pipeline/pipelines/results/page/1

**Comment by jakub-kubera** [comment]
merged into opsd demo repo 
https://github.com/opsd-io/digitalocean-infra-demo/pull/87
